spring:
  application:
    name: l2-redis2
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ""
    password: ""
    url: ""
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true